export const tests = [
    'get started link',
    'should allow me to add todo items',
    'should clear text input field when an item is added',
    'should allow me to add todo items',
    'should append new items to the bottom of the list',
    'should allow me to mark all items as completed',
    'should allow me to clear the complete state of all items',
    'complete all checkbox should update state when items are completed / cleared',
    'should allow me to mark items as complete',
    'should allow me to un-mark items as complete',
    'should allow me to edit an item',
    'should hide other controls when editing',
    'should save edits on blur',
    'should trim entered text',
    'should remove the item if an empty text string was entered',
    'should cancel edits on escape',
    'should display the current number of todo items',
    'should display the correct text',
    'should remove completed items when clicked',
    'should be hidden when there are no items that are completed',
    'should persist its data',
    'should allow me to display active items',
    'should respect the back button',
    'should allow me to display completed items',
    'should allow me to display all items',
    'should highlight the currently applied filter',
]
